const fs = require("fs/promises");
const path = require("path");
const unitsArray = require("./units.js");

const filePath = path.join("src", "units", "index.js");

let string = `/** This file is autogenerated. Don't modify! */
export const units = [`;

for (const { name, idBaseUnit, units } of unitsArray) {
  let stringObject = `{ name: _("${name}"), idBaseUnit: "${idBaseUnit}", units: [`;
  for (const { id, label, toBaseFactor, symbol } of units) {
    stringObject += `{ id: "${id}", label: _("${label}"), toBaseFactor: "${toBaseFactor}", symbol: { short: "${symbol.short}"}},`;
  }
  stringObject += `]},`;
  string += stringObject;
}

string += `]`;

async function saveData(data) {
  try {
    await fs.writeFile(filePath, data, "utf-8");
  } catch (error) {}
}

saveData(string)
  .then(() => {
    console.log("Saved data successfully");
  })
  .catch((error) => {
    console.error(error);
  });

