/**
 * This is where you should add new units.
 * Do not modify src/data/index.js because
 * it is autogenerated.
 *
 */

module.exports = [
  {
    label: "Length",
    idBaseUnit: "meter",
    units: [
      {
        id: "meter",
        label: "Meters",
        toBaseFactor: "1",
        symbols: {
          full: "meter",
          short: "m",
          plural: "meters",
        },
      },
      {
        id: "kilometer",
        label: "Kilometers",
        toBaseFactor: "1000",
        symbols: {
          full: "kilometer",
          short: "km",
          plural: "kilometers",
        },
      },
      {
        id: "centimeter",
        label: "Centimeters",
        toBaseFactor: "0.01",
        symbols: {
          full: "centimeter",
          short: "cm",
          plural: "centimeters",
        },
      },
      {
        id: "millimeter",
        label: "Millimeters",
        toBaseFactor: "0.001",
        symbols: {
          full: "millimeter",
          short: "mm",
          plural: "millimeters",
        },
      },
      {
        id: "mile",
        label: "Miles",
        toBaseFactor: "1609.344",
        symbols: {
          full: "mile",
          short: "mi",
          plural: "miles",
        },
      },
      {
        id: "yard",
        label: "Yards",
        toBaseFactor: "0.9144",
        symbols: {
          full: "yard",
          short: "yd",
          plural: "yards",
        },
      },
      {
        id: "feet",
        label: "Feet",
        toBaseFactor: "0.3048",
        symbols: {
          full: "foot",
          short: "ft",
          plural: "feet",
        },
      },
      {
        id: "inch",
        label: "Inches",
        toBaseFactor: "0.0254",
        symbols: {
          full: "inch",
          short: "in",
          plural: "inches",
        },
      },
    ],
  },
  {
    label: "Area",
    idBaseUnit: "square_meter",
    units: [
      {
        id: "square_meter",
        label: "Square Meters",
        toBaseFactor: "1",
        symbols: {
          full: "square meter",
          short: "m&lt;sup&gt;2&lt;/sup&gt;",
          plural: "square meters",
        },
      },
      {
        id: "square_kilometer",
        label: "Square Kilometers",
        toBaseFactor: "1000000",
        symbols: {
          full: "kilometer",
          short: "km&lt;sup&gt;2&lt;/sup&gt;",
          plural: "kilometers",
        },
      },
      {
        id: "square_centimeter",
        label: "Square Centimeters",
        toBaseFactor: "0.0001",
        symbols: {
          full: "square centimeter",
          short: "cm&lt;sup&gt;2&lt;/sup&gt;",
          plural: "square centimeters",
        },
      },
      {
        id: "square_millimeter",
        label: "Square Millimeters",
        toBaseFactor: "0.000001",
        symbols: {
          full: "square millimeter",
          short: "mm&lt;sup&gt;2&lt;/sup&gt;",
          plural: "square millimeters",
        },
      },
      {
        id: "square_mile",
        label: "Square Miles",
        toBaseFactor: "2589988.110336",
        symbols: {
          full: "square mile",
          short: "mi&lt;sup&gt;2&lt;/sup&gt;",
          plural: "square miles",
        },
      },
      {
        id: "square yard",
        label: "Square Yards",
        toBaseFactor: "0.83612736",
        symbols: {
          full: "square yard",
          short: "yd&lt;sup&gt;2&lt;/sup&gt;",
          plural: "square yards",
        },
      },
      {
        id: "square_feet",
        label: "Square Feet",
        toBaseFactor: "0.09290304",
        symbols: {
          full: "square foot",
          short: "ft&lt;sup&gt;2&lt;/sup&gt;",
          plural: "square feet",
        },
      },
      {
        id: "square_inch",
        label: "Square Inches",
        toBaseFactor: "0.00064516",
        symbols: {
          full: "square inch",
          short: "in&lt;sup&gt;2&lt;/sup&gt;",
          plural: "square inches",
        },
      },
    ],
  },
  {
    label: "Volume",
    idBaseUnit: "liter",
    units: [
      {
        id: "liter",
        label: "Liters",
        toBaseFactor: "1",
        symbols: {
          full: "liter",
          short: "L",
          plural: "liters",
        },
      },
      {
        id: "milliliter",
        label: "Milliliters",
        toBaseFactor: "0.001",
        symbols: {
          full: "milliliter",
          short: "mL",
          plural: "milliliters",
        },
      },
      {
        id: "gallon",
        label: "Gallons",
        toBaseFactor: "3.785411784",
        symbols: {
          full: "gallon",
          short: "gal",
          plural: "gallons",
        },
      },
    ],
  },
  {
    label: "Speed",
    idBaseUnit: "meters_per_second",
    units: [
      {
        id: "meters_per_second",
        label: "Meters per Second",
        toBaseFactor: "1",
        symbols: {
          full: "meter per second",
          short: "m/s",
          plural: "meters per second",
        },
      },
      {
        id: "kilometers_per_hour",
        label: "Kilometers per Hour",
        toBaseFactor: "0.277777778",
        symbols: {
          full: "kilometer per hour",
          short: "km/h",
          plural: "kilometers per hour",
        },
      },
      {
        id: "mile_per_hour",
        label: "Miles per Hour",
        toBaseFactor: "0.44704",
        symbols: {
          full: "mile per hour",
          short: "mph",
          plural: "miles per hour",
        },
      },
    ],
  },
  {
    label: "Time",
    idBaseUnit: "seconds",
    units: [
      {
        id: "seconds",
        label: "Seconds",
        toBaseFactor: "1",
        symbols: {
          full: "Second",
          short: "s",
          plural: "Seconds",
        },
      },
      {
        id: "minutes",
        label: "Minutes",
        toBaseFactor: "60",
        symbols: {
          full: "Minute",
          short: "m",
          plural: "Minutes",
        },
      },
      {
        id: "hours",
        label: "Hours",
        toBaseFactor: "3600",
        symbols: {
          full: "Hour",
          short: "h",
          plural: "Hours",
        },
      },
      {
        id: "days",
        label: "Days",
        toBaseFactor: "86400",
        symbols: {
          full: "Day",
          short: "d",
          plural: "Days",
        },
      },
    ],
  },
];
