/**
 * This is where you should add new units.
 * Do not modify src/data/index.js because
 * it is autogenerated.
 *
 */

module.exports = [
  {
    name: "Length",
    idBaseUnit: "meter",
    units: [
      {
        id: "meter",
        label: "Meters",
        toBaseFactor: "1",
        symbol: {
          full: "meter",
          short: "m",
          plural: "meters",
        },
      },
      {
        id: "kilometer",
        label: "Kilometers",
        toBaseFactor: "1000",
        symbol: {
          full: "kilometer",
          short: "km",
          plural: "kilometers",
        },
      },
      {
        id: "centimeter",
        label: "Centimeters",
        toBaseFactor: "0.01",
        symbol: {
          full: "centimeter",
          short: "cm",
          plural: "centimeters",
        },
      },
      {
        id: "mile",
        label: "Miles",
        toBaseFactor: "1609.344",
        symbol: {
          full: "mile",
          short: "mi",
          plural: "miles",
        },
      },
    ],
  },
  {
    name: "Volume",
    idBaseUnit: "liter",
    units: [
      {
        id: "liter",
        label: "Liters",
        toBaseFactor: "1",
        symbol: {
          full: "liter",
          short: "L",
          plural: "liters",
        },
      },
      {
        id: "milliliter",
        label: "Milliliters",
        toBaseFactor: "0.001",
        symbol: {
          full: "milliliter",
          short: "mL",
          plural: "milliliters",
        },
      },
      {
        id: "gallon",
        label: "Gallons",
        toBaseFactor: "3.785411784",
        symbol: {
          full: "gallon",
          short: "gal",
          plural: "gallons",
        },
      },
    ],
  },
  {
    name: "Speed",
    idBaseUnit: "meters_per_second",
    units: [
      {
        id: "meters_per_second",
        label: "Meters per Second",
        toBaseFactor: "1",
        symbol: {
          full: "meter per second",
          short: "m/s",
          plural: "meters per second",
        },
      },
      {
        id: "kilometers_per_hour",
        label: "Kilometers per Hour",
        toBaseFactor: "0.277777778",
        symbol: {
          full: "kilometer per hour",
          short: "km/h",
          plural: "kilometers per hour",
        },
      },
      {
        id: "mile_per_hour",
        label: "Miles per Hour",
        toBaseFactor: "0.44704",
        symbol: {
          full: "mile per hour",
          short: "mph",
          plural: "miles per hour",
        },
      },
    ],
  },
];
